fastp_trim:
  cpu: 2
  queue: normal
bowtie2_map:
  cpu: 8
  queue: normal
sam2bam:
  cpu: 8
  queue: normal
MarkDup:
  cpu: 1
  queue: normal
bam_index:
  cpu: 1
  queue: normal
bam2bw:
  cpu: 1
  queue: normal
callpeak:
  cpu: 1
  queue: normal
Annotation_peaks:
  cpu: 1
  queue: normal